default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: phone_catalog_development
  username: postgres
  password: 4421
  host: localhost
  port: 5432

test:
  <<: *default
  database: phone_catalog_test
  username: postgres
  password: 4421
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: phone_catalog_production
    username: phone_catalog
    password: <%= ENV["PHONE_CATALOG_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: phone_catalog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: phone_catalog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: phone_catalog_production_cable
    migrations_paths: db/cable_migrate
