default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: phone_catalog_development
  username: postgres
  password: 4421
  host: localhost
  port: 5432

test:
  test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'phone_catalog_test_coverage') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '4421') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

production:
  primary: &primary_production
    <<: *default
    database: phone_catalog_production
    username: phone_catalog
    password: <%= ENV["PHONE_CATALOG_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: phone_catalog_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: phone_catalog_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: phone_catalog_production_cable
    migrations_paths: db/cable_migrate
