name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Instalar dependências do sistema
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Configurar chave do Rails
        run: |
          echo "${{ secrets.RAILS_MASTER_KEY }}" > config/master.key
          chmod 600 config/master.key

      - name: Instalar dependências JS
        run: npm install

      - name: Compilar assets
        run: |
          npm run build
          npm run build:css || echo "CSS não configurado com Tailwind"

      - name: Prepara o banco de dados
        run: bin/rails db:test:prepare

      - name: Executar testes com RSpec e gerar cobertura
        run: bundle exec rspec

      - name: Upload para Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/.resultset.json
          flags: rspec
          name: codecov-coverage-only
          fail_ci_if_error: true
